/**
 * QUANTUM COMPLIANCE OS™ — agencyHelpers.js
 * Run 13: Agency + White Label Settings — Helper Functions
 * =========================================================
 * Pure helper functions for agency settings, white-label config,
 * portfolio analytics preview, and tier capability checks.
 *
 * All helpers fail safely — if data is missing or malformed, they return
 * sensible empty/zero defaults and never throw.
 *
 * No side effects. No localStorage access. No state mutations.
 * Safe to import anywhere.
 *
 * IMPORTANT DISCLAIMER:
 * White-label settings control presentation only in this run and do not
 * create certified compliance outputs. Risk scores and recommendations
 * are advisory and require qualified human review.
 *
 * Powered by 4P3X Intelligent AI™ — Created by Kyzel Kreates™
 */

import { canUseFeature, FEATURE_KEYS, getPlanById } from './plans.js';

// ─── Default agency settings ──────────────────────────────────────────────────
export function getDefaultAgencySettings() {
  return {
    agencyName:                'Demo Quantum Advisory Group',
    agencyDisplayName:         'Demo Quantum Advisory Group',
    agencyLogoUrl:             '',
    agencyPrimaryColor:        '#D4AF37',
    agencySecondaryColor:      '#C0C0C0',
    agencyAccentColor:         '#7C3AED',
    agencyContactName:         'Demo Consultant',
    agencyContactEmail:        'consultant@example.com',
    agencyWebsite:             '',
    agencySectorFocus:         ['SMEs', 'Manufacturing', 'Financial Services', 'Healthcare', 'Public Sector'],
    agencyTier:                'agency',
    clientLimit:               50,
    whiteLabelReportsEnabled:  true,
    portfolioAnalyticsEnabled: true,
    clientArchiveEnabled:      true,
    priorityActionsEnabled:    true,
    isDemo:                    true,
    updatedAt:                 '2026-06-04',
  };
}

// ─── Default white-label settings ─────────────────────────────────────────────
export function getDefaultWhiteLabelSettings() {
  return {
    enabled:                       false,
    mode:                          'preview',    // preview | client-facing | internal-protected
    publicProductName:             'Quantum Compliance OS™',
    publicBrandLine:               'Powered by 4P3X Intelligent AI™ Created by Kyzel Kreates™',
    internalOwnershipLine:         'Platform architecture by Kyzel Kreates™',
    allowClientFacingWhiteLabel:   true,
    showKyzelBrandingInReports:    true,
    showKyzelBrandingInInternalApp:true,
    customDomainReady:             false,
    customDomainValue:             '',
    onboardingWizardEnabled:       false,
    slaSupportLayerEnabled:        false,
    supportEmail:                  '',
    isDemo:                        true,
    updatedAt:                     '2026-06-04',
  };
}

// ─── Agency tier capability checks ───────────────────────────────────────────
export function getAgencyTierStatus(activePlanId) {
  const plan = getPlanById(activePlanId);
  return {
    planId:                    activePlanId,
    planName:                  plan?.name || 'Starter',
    hasWhiteLabelReports:      canUseFeature(activePlanId, FEATURE_KEYS.WHITE_LABEL_REPORTS),
    hasClientArchive:          canUseFeature(activePlanId, FEATURE_KEYS.CLIENT_ARCHIVE),
    hasPortfolioAnalytics:     canUseFeature(activePlanId, FEATURE_KEYS.PORTFOLIO_ANALYTICS),
    hasPriorityActions:        canUseFeature(activePlanId, FEATURE_KEYS.PRIORITY_ACTIONS),
    hasFullWhiteLabel:         canUseFeature(activePlanId, FEATURE_KEYS.FULL_WHITE_LABEL_MODE),
    hasCustomDomain:           canUseFeature(activePlanId, FEATURE_KEYS.CUSTOM_DOMAIN_READY),
    hasOnboardingWizard:       canUseFeature(activePlanId, FEATURE_KEYS.ONBOARDING_WIZARD),
    hasSlaSupportLayer:        canUseFeature(activePlanId, FEATURE_KEYS.SLA_SUPPORT_LAYER),
  };
}

export function getWhiteLabelPreviewSettings(whiteLabelSettings, agencySettings) {
  const wl = whiteLabelSettings || getDefaultWhiteLabelSettings();
  const ag = agencySettings    || getDefaultAgencySettings();
  return {
    enabled:           wl.enabled,
    mode:              wl.mode,
    displayName:       wl.enabled ? (ag.agencyDisplayName || ag.agencyName) : wl.publicProductName,
    brandLine:         wl.showKyzelBrandingInReports ? wl.publicBrandLine : (ag.agencyName || wl.publicBrandLine),
    ownershipLine:     wl.internalOwnershipLine,
    primaryColor:      wl.enabled ? ag.agencyPrimaryColor : '#D4AF37',
    reportFooter:      `Generated by ${wl.publicProductName} — ${wl.publicBrandLine}`,
  };
}

// ─── Portfolio analytics helpers ──────────────────────────────────────────────

/**
 * Full portfolio analytics summary from local/demo client + report/evidence data.
 */
export function getAgencyPortfolioSummary(clients = [], reports = [], evidenceItems = []) {
  const safe = (arr) => (Array.isArray(arr) ? arr : []);
  const allClients  = safe(clients);
  const allReports  = safe(reports);
  const allEvidence = safe(evidenceItems);

  const active   = allClients.filter((c) => !c.archived && c.status !== 'archived');
  const archived = allClients.filter((c) =>  c.archived || c.status === 'archived');

  const qScores = active.map((c) => c.quantumReadinessScore).filter((s) => s != null);
  const sScores = active.map((c) => c.securityScore).filter((s) => s != null);

  const missingEvidence = allEvidence.filter((e) => ['missing','incomplete'].includes(e.status)).length;

  const avgQ  = qScores.length ? Math.round(qScores.reduce((a,b)=>a+b,0)/qScores.length) : null;
  const avgS  = sScores.length ? Math.round(sScores.reduce((a,b)=>a+b,0)/sScores.length) : null;
  const highRisk = active.filter((c) => c.riskLevel === 'high').length;

  // evidence completion per client → average
  const evComps = active.map((c) => {
    const items = allEvidence.filter((e) => e.clientId === c.id && e.status !== 'not-required');
    if (!items.length) return null;
    const score = items.reduce((acc,e) => acc + (e.status==='complete'?100:e.status==='partial'?50:0), 0);
    return Math.round(score / items.length);
  }).filter((s) => s != null);
  const avgEv = evComps.length ? Math.round(evComps.reduce((a,b)=>a+b,0)/evComps.length) : null;

  return {
    totalClients:           allClients.length,
    activeClients:          active.length,
    archivedClients:        archived.length,
    highRiskClients:        highRisk,
    avgQuantumScore:        avgQ,
    avgSecurityScore:       avgS,
    avgEvidenceCompletion:  avgEv,
    totalReports:           allReports.length,
    missingEvidenceItems:   missingEvidence,
    // priority actions = quick-count from risk thresholds
    priorityActionCount:    active.filter((c) =>
      c.riskLevel === 'high' || (c.securityScore != null && c.securityScore < 50) ||
      (c.quantumReadinessScore != null && c.quantumReadinessScore < 30) ||
      c.assessmentStatus === 'review-needed'
    ).length,
  };
}

export function getArchivedClientCount(clients = []) {
  return (clients||[]).filter((c) => c.archived || c.status === 'archived').length;
}

export function getAgencyAverageQuantumScore(clients = []) {
  const scores = (clients||[]).filter((c)=>!c.archived).map((c)=>c.quantumReadinessScore).filter((s)=>s!=null);
  return scores.length ? Math.round(scores.reduce((a,b)=>a+b,0)/scores.length) : null;
}

export function getAgencyAverageSecurityScore(clients = []) {
  const scores = (clients||[]).filter((c)=>!c.archived).map((c)=>c.securityScore).filter((s)=>s!=null);
  return scores.length ? Math.round(scores.reduce((a,b)=>a+b,0)/scores.length) : null;
}

export function getAgencyReportCount(reports = []) {
  return (reports||[]).length;
}

export function getAgencyMissingEvidenceCount(evidenceItems = []) {
  return (evidenceItems||[]).filter((e) => ['missing','incomplete'].includes(e.status)).length;
}

export function getAgencyPriorityActions(clients = [], evidenceItems = [], reports = []) {
  const active = (clients||[]).filter((c)=>!c.archived && c.status!=='archived');
  return active.filter((c) =>
    c.riskLevel === 'high' ||
    (c.securityScore != null && c.securityScore < 50) ||
    (c.quantumReadinessScore != null && c.quantumReadinessScore < 30) ||
    c.assessmentStatus === 'review-needed' ||
    (evidenceItems||[]).some((e)=>e.clientId===c.id && e.status==='missing')
  ).length;
}

export function getAgencyEvidenceCompletion(clients = [], evidenceItems = []) {
  const active = (clients||[]).filter((c)=>!c.archived && c.status!=='archived');
  const comps = active.map((c) => {
    const items = (evidenceItems||[]).filter((e)=>e.clientId===c.id && e.status!=='not-required');
    if (!items.length) return null;
    const score = items.reduce((acc,e)=>acc+(e.status==='complete'?100:e.status==='partial'?50:0),0);
    return Math.round(score/items.length);
  }).filter((s)=>s!=null);
  return comps.length ? Math.round(comps.reduce((a,b)=>a+b,0)/comps.length) : null;
}
