/**
 * QUANTUM COMPLIANCE OS™ — targetAssessmentRules.js
 * Run 9: Target Assessment Engine
 *
 * Passive-only, defensive, advisory rules.
 * No offensive scanning. No exploit checks. No credential testing.
 * No payload injection. No automated crawling. No unauthorised scanning.
 *
 * All checks are manual/questionnaire-based or passive observation.
 * Browser-based checks are limited by CORS — clearly stated where relevant.
 */

// ─── Target Types ─────────────────────────────────────────────────────────────
export const TARGET_TYPES = [
  { value: 'website',        label: 'Website' },
  { value: 'web_app',        label: 'Web App' },
  { value: 'saas_platform',  label: 'SaaS Platform' },
  { value: 'internal_system',label: 'Internal System' },
  { value: 'api',            label: 'API' },
  { value: 'cloud_env',      label: 'Cloud Environment' },
  { value: 'manual_only',    label: 'Manual Evidence-Only Assessment' },
];

// ─── Assessment Modes ─────────────────────────────────────────────────────────
export const SCAN_MODES = [
  { value: 'passive_web',        label: 'Passive Web Review' },
  { value: 'header_tls_dns',     label: 'Header / TLS / DNS Checklist' },
  { value: 'manual_evidence',    label: 'Manual Evidence Review' },
  { value: 'api_config',         label: 'API Configuration Review' },
  { value: 'compliance_q',       label: 'Compliance Questionnaire Only' },
  { value: 'quantum_q',          label: 'Quantum-Readiness Questionnaire Only' },
];

// ─── Target Status Values ──────────────────────────────────────────────────────
export const TARGET_STATUSES = [
  'draft',
  'awaiting_authorisation',
  'ready_for_review',
  'in_review',
  'recommendations_generated',
  'evidence_required',
  'report_ready',
  'closed',
  'accepted_risk',
];

export const TARGET_STATUS_LABELS = {
  draft:                       'Draft',
  awaiting_authorisation:      'Awaiting Authorisation',
  ready_for_review:            'Ready for Review',
  in_review:                   'In Review',
  recommendations_generated:   'Recommendations Generated',
  evidence_required:           'Evidence Required',
  report_ready:                'Report Ready',
  closed:                      'Closed',
  accepted_risk:               'Accepted Risk',
};

// Allowed status transitions — used to validate state machine
export const STATUS_TRANSITIONS = {
  draft:                       ['awaiting_authorisation'],
  awaiting_authorisation:      ['ready_for_review'],   // only if authorisationConfirmed
  ready_for_review:            ['in_review'],
  in_review:                   ['recommendations_generated'],
  recommendations_generated:   ['evidence_required', 'accepted_risk'],
  evidence_required:           ['report_ready'],
  report_ready:                ['closed'],
  closed:                      [],
  accepted_risk:               [],
};

// ─── Finding Categories ───────────────────────────────────────────────────────
export const FINDING_CATEGORIES = [
  'Security Headers',
  'TLS / Encryption',
  'Authentication',
  'Data Protection',
  'Backup / Recovery',
  'Vendor Risk',
  'Quantum Readiness',
  'Evidence Gap',
  'Compliance Gap',
  'Operational Risk',
  'API Configuration',
  'Cloud Configuration',
  'Manual Review',
];

export const RISK_LEVELS = ['Low', 'Medium', 'High', 'Critical'];
export const CONFIDENCE_LEVELS = ['Low', 'Medium', 'High'];
export const FINDING_STATUSES = ['Open', 'In Progress', 'Resolved', 'Accepted Risk', 'Wont Fix'];

// ─── Passive Checklist Sections ───────────────────────────────────────────────
// Each check item: id, label, hint, category, riskIfNo, appliesTo (target types array, empty = all)
export const CHECKLIST_SECTIONS = [
  {
    id: 'web_presence',
    label: 'Web Presence',
    icon: '🌐',
    items: [
      {
        id: 'https_present',
        label: 'HTTPS is present and enforced',
        hint: 'The site redirects HTTP to HTTPS. No mixed content warnings visible.',
        category: 'TLS / Encryption',
        riskIfNo: 'High',
        appliesTo: ['website', 'web_app', 'saas_platform'],
      },
      {
        id: 'privacy_policy',
        label: 'Privacy policy page is present and accessible',
        hint: 'A privacy policy page exists, is findable, and covers data handling.',
        category: 'Compliance Gap',
        riskIfNo: 'Medium',
        appliesTo: ['website', 'web_app', 'saas_platform'],
      },
      {
        id: 'terms_page',
        label: 'Terms of service / acceptable use page is present',
        hint: 'Terms or acceptable use policy page exists and is accessible.',
        category: 'Compliance Gap',
        riskIfNo: 'Low',
        appliesTo: ['website', 'web_app', 'saas_platform'],
      },
      {
        id: 'contact_page',
        label: 'Contact page or security contact is available',
        hint: 'Users can find a way to report issues or contact the organisation.',
        category: 'Operational Risk',
        riskIfNo: 'Low',
        appliesTo: ['website', 'web_app', 'saas_platform'],
      },
      {
        id: 'robots_txt',
        label: 'robots.txt is present (manually checked or declared)',
        hint: 'A robots.txt file exists at the domain root. Review for unintended path exposure.',
        category: 'Operational Risk',
        riskIfNo: 'Low',
        appliesTo: ['website', 'web_app', 'saas_platform'],
      },
    ],
  },
  {
    id: 'headers_browser_security',
    label: 'Headers & Browser Security',
    icon: '🛡️',
    items: [
      {
        id: 'csp_header',
        label: 'Content-Security-Policy (CSP) header is present and configured',
        hint: 'A CSP header restricts which scripts, styles, frames, and resources the browser can load.',
        category: 'Security Headers',
        riskIfNo: 'Medium',
        appliesTo: ['website', 'web_app', 'saas_platform'],
        finding: {
          title: 'Missing or unverified Content-Security-Policy header',
          businessImpact: 'May increase exposure to script injection and client-side attack risk.',
          technicalExplanation: 'A Content-Security-Policy header helps restrict which scripts, styles, frames, and resources a browser can load. Without it, the application is more exposed to cross-site scripting (XSS) and data injection attacks.',
          complianceRelevance: 'Supports secure configuration evidence for ISO 27001, NCSC Cyber Essentials, and similar frameworks.',
          quantumReadinessRelevance: 'Not directly quantum-related, but improves baseline security posture before post-quantum migration.',
          recommendedFix: 'Add a Content-Security-Policy header. Begin in report-only mode, test thoroughly, then switch to enforce mode.',
          evidenceRequired: 'Header export, screenshot of HTTP response headers, or server configuration evidence.',
        },
      },
      {
        id: 'hsts_header',
        label: 'HTTP Strict Transport Security (HSTS) header is present',
        hint: 'HSTS instructs browsers to only connect via HTTPS. Check for Strict-Transport-Security in response headers.',
        category: 'Security Headers',
        riskIfNo: 'Medium',
        appliesTo: ['website', 'web_app', 'saas_platform'],
        finding: {
          title: 'HTTP Strict Transport Security (HSTS) not confirmed',
          businessImpact: 'Without HSTS, users may connect over insecure HTTP if HTTPS is misconfigured or bypassed.',
          technicalExplanation: 'The Strict-Transport-Security header instructs browsers to enforce HTTPS for all future connections. Without it, downgrade attacks and SSL stripping are easier.',
          complianceRelevance: 'Required or recommended under multiple frameworks including NCSC Cyber Essentials, PCI-DSS, and ISO 27001.',
          quantumReadinessRelevance: 'TLS/encryption posture is critical for post-quantum migration planning.',
          recommendedFix: 'Add Strict-Transport-Security: max-age=31536000; includeSubDomains to your web server configuration.',
          evidenceRequired: 'HTTP response header export or screenshot confirming HSTS is present.',
        },
      },
      {
        id: 'xframe_header',
        label: 'X-Frame-Options or frame-ancestors CSP directive is set',
        hint: 'Prevents the page from being embedded in iframes on other origins (clickjacking protection).',
        category: 'Security Headers',
        riskIfNo: 'Medium',
        appliesTo: ['website', 'web_app', 'saas_platform'],
        finding: {
          title: 'X-Frame-Options or frame-ancestors directive not confirmed',
          businessImpact: 'Without clickjacking protection, malicious sites may embed your application in a hidden iframe to capture user interactions.',
          technicalExplanation: 'X-Frame-Options: DENY or SAMEORIGIN, or a frame-ancestors CSP directive, prevents your pages from being loaded inside frames on other origins.',
          complianceRelevance: 'Part of secure browser configuration requirements.',
          quantumReadinessRelevance: 'Baseline security hardening — not directly quantum-related.',
          recommendedFix: 'Add X-Frame-Options: DENY or use a CSP frame-ancestors directive. Test to ensure your own embedded content is not broken.',
          evidenceRequired: 'HTTP response header export confirming frame protection is present.',
        },
      },
      {
        id: 'xcontent_type',
        label: 'X-Content-Type-Options: nosniff header is present',
        hint: 'Prevents browsers from MIME-sniffing a response away from the declared content type.',
        category: 'Security Headers',
        riskIfNo: 'Low',
        appliesTo: ['website', 'web_app', 'saas_platform'],
        finding: {
          title: 'X-Content-Type-Options header not confirmed',
          businessImpact: 'Browser MIME sniffing can allow unexpected content to be executed as scripts.',
          technicalExplanation: 'X-Content-Type-Options: nosniff prevents browsers from guessing the MIME type and executing files in unexpected ways.',
          complianceRelevance: 'Basic hardening — referenced in multiple security configuration guides.',
          quantumReadinessRelevance: 'Baseline security — not directly quantum-related.',
          recommendedFix: 'Add X-Content-Type-Options: nosniff to your web server headers.',
          evidenceRequired: 'HTTP response header export confirming the header is present.',
        },
      },
      {
        id: 'referrer_policy',
        label: 'Referrer-Policy header is present and restrictive',
        hint: 'Controls how much referrer information is sent with requests. Helps prevent information leakage.',
        category: 'Security Headers',
        riskIfNo: 'Low',
        appliesTo: ['website', 'web_app', 'saas_platform'],
      },
      {
        id: 'cookie_secure',
        label: 'Cookies are marked Secure and HttpOnly where applicable',
        hint: 'Session and authentication cookies should have Secure and HttpOnly flags set.',
        category: 'Security Headers',
        riskIfNo: 'High',
        appliesTo: ['website', 'web_app', 'saas_platform'],
        finding: {
          title: 'Cookies not confirmed as Secure and HttpOnly',
          businessImpact: 'Insecure cookies can be intercepted over HTTP or accessed by malicious scripts.',
          technicalExplanation: 'Session cookies should have the Secure flag (only sent over HTTPS) and HttpOnly flag (inaccessible to JavaScript) to reduce theft risk.',
          complianceRelevance: 'Cookie security is referenced in OWASP Top 10, NCSC guidance, and multiple compliance frameworks.',
          quantumReadinessRelevance: 'Session management is part of baseline security posture.',
          recommendedFix: 'Review all cookies, particularly session and authentication cookies. Apply Secure, HttpOnly, and SameSite attributes as appropriate.',
          evidenceRequired: 'Cookie inspection screenshot or exported cookie attributes from browser DevTools.',
        },
      },
    ],
  },
  {
    id: 'authentication',
    label: 'Authentication',
    icon: '🔐',
    items: [
      {
        id: 'login_page_observed',
        label: 'Login page or authenticated area exists',
        hint: 'Confirm whether the target has a login/authentication flow.',
        category: 'Authentication',
        riskIfNo: null,
        appliesTo: [],
      },
      {
        id: 'mfa_available',
        label: 'Multi-Factor Authentication (MFA) is available for users',
        hint: 'MFA should be available and ideally enforced for all privileged accounts.',
        category: 'Authentication',
        riskIfNo: 'High',
        appliesTo: [],
        finding: {
          title: 'Multi-Factor Authentication (MFA) not confirmed or not available',
          businessImpact: 'Without MFA, accounts are significantly more vulnerable to credential-based attacks.',
          technicalExplanation: 'MFA adds a second layer of verification beyond a password, dramatically reducing account takeover risk from phishing, credential stuffing, and brute force attacks.',
          complianceRelevance: 'Required or strongly recommended by ISO 27001, NCSC Cyber Essentials, and most modern compliance frameworks.',
          quantumReadinessRelevance: 'Password-based authentication is particularly vulnerable post-quantum. MFA is an important interim control.',
          recommendedFix: 'Enable MFA for all accounts — at minimum for privileged and admin accounts. Prefer authenticator apps or hardware tokens over SMS.',
          evidenceRequired: 'Screenshot of MFA settings or authentication configuration documentation.',
        },
      },
      {
        id: 'mfa_enforced',
        label: 'MFA is enforced for admin or privileged accounts',
        hint: 'Confirm that MFA is mandatory for elevated access accounts.',
        category: 'Authentication',
        riskIfNo: 'Critical',
        appliesTo: [],
      },
      {
        id: 'password_policy',
        label: 'Password policy enforces minimum length and complexity',
        hint: 'A password policy requiring minimum length, complexity, or passphrase guidance is in place.',
        category: 'Authentication',
        riskIfNo: 'Medium',
        appliesTo: [],
        finding: {
          title: 'Password policy not confirmed or insufficient',
          businessImpact: 'Weak password policies increase credential compromise risk.',
          technicalExplanation: 'A strong password policy enforces minimum length (12+ characters), discourages common passwords, and may check against known breach lists.',
          complianceRelevance: 'Required under NCSC Cyber Essentials, ISO 27001, and most compliance frameworks.',
          quantumReadinessRelevance: 'Classical password attacks are amplified post-quantum for weaker credentials.',
          recommendedFix: 'Implement a password policy requiring 12+ character passphrases, check against known-breached passwords, and enforce MFA to compensate for password weaknesses.',
          evidenceRequired: 'Password policy documentation or screenshot of policy settings.',
        },
      },
      {
        id: 'account_lockout',
        label: 'Account lockout or rate limiting is in place for failed logins',
        hint: 'After N failed login attempts, the account locks or requests are rate-limited.',
        category: 'Authentication',
        riskIfNo: 'Medium',
        appliesTo: [],
      },
    ],
  },
  {
    id: 'encryption',
    label: 'TLS & Encryption',
    icon: '🔑',
    items: [
      {
        id: 'tls_version',
        label: 'TLS 1.2 or 1.3 is in use (TLS 1.0/1.1 disabled)',
        hint: 'Outdated TLS versions (1.0, 1.1) have known vulnerabilities and should be disabled.',
        category: 'TLS / Encryption',
        riskIfNo: 'High',
        appliesTo: ['website', 'web_app', 'saas_platform', 'api'],
        finding: {
          title: 'TLS version not confirmed or potentially outdated',
          businessImpact: 'Outdated TLS exposes data in transit to downgrade attacks and known vulnerabilities.',
          technicalExplanation: 'TLS 1.0 and 1.1 are deprecated and have known vulnerabilities. TLS 1.2 is acceptable; TLS 1.3 is recommended for new deployments.',
          complianceRelevance: 'Required by PCI-DSS, ISO 27001, NCSC guidance, and most modern compliance standards.',
          quantumReadinessRelevance: 'TLS is a key area for post-quantum migration. TLS 1.3 with NIST-approved algorithms is the foundation for PQC readiness.',
          recommendedFix: 'Disable TLS 1.0 and 1.1. Enforce TLS 1.2 as minimum; prefer TLS 1.3. Plan for post-quantum TLS algorithm migration.',
          evidenceRequired: 'TLS configuration report, SSL Labs result, or server configuration export.',
        },
      },
      {
        id: 'cert_valid',
        label: 'SSL/TLS certificate is valid and not near expiry',
        hint: 'Certificate is issued by a trusted CA, not expired, and not expiring within 30 days.',
        category: 'TLS / Encryption',
        riskIfNo: 'High',
        appliesTo: ['website', 'web_app', 'saas_platform', 'api'],
        finding: {
          title: 'TLS certificate validity not confirmed',
          businessImpact: 'An expired or invalid certificate breaks HTTPS and erodes user and system trust.',
          technicalExplanation: 'TLS certificates must be valid, issued by a trusted CA, and not expired. Automated renewal (Let\'s Encrypt / ACM) is strongly recommended.',
          complianceRelevance: 'Valid certificates are a basic requirement for secure communications under all major frameworks.',
          quantumReadinessRelevance: 'Certificate management and algorithm agility are key to PQC migration readiness.',
          recommendedFix: 'Verify certificate validity. Implement automated renewal. Review certificate expiry monitoring.',
          evidenceRequired: 'Screenshot of certificate details or automated monitoring confirmation.',
        },
      },
      {
        id: 'encryption_at_rest',
        label: 'Data at rest is encrypted (storage-level encryption confirmed)',
        hint: 'Databases, file stores, and backups use encryption at rest.',
        category: 'TLS / Encryption',
        riskIfNo: 'High',
        appliesTo: [],
        finding: {
          title: 'Encryption at rest not confirmed',
          businessImpact: 'Unencrypted stored data is exposed if physical or logical access is compromised.',
          technicalExplanation: 'All sensitive data should be encrypted at rest using AES-256 or equivalent. This applies to databases, file stores, backups, and any persistent storage.',
          complianceRelevance: 'Required by ISO 27001, GDPR, PCI-DSS, and most data protection frameworks.',
          quantumReadinessRelevance: 'Current symmetric encryption (AES-256) is considered quantum-resistant. RSA/ECC-based encryption at rest is not.',
          recommendedFix: 'Confirm encryption at rest is enabled for all data stores. Review key management practices. Replace RSA/ECC with quantum-safe alternatives where used for data at rest protection.',
          evidenceRequired: 'Cloud provider encryption configuration, database encryption settings, or storage policy documentation.',
        },
      },
      {
        id: 'pqc_assessment',
        label: 'Post-quantum cryptography (PQC) migration has been assessed',
        hint: 'The organisation has reviewed which cryptographic algorithms are in use and assessed PQC migration readiness.',
        category: 'Quantum Readiness',
        riskIfNo: 'High',
        appliesTo: [],
        finding: {
          title: 'Post-quantum cryptography (PQC) migration not assessed for this target',
          businessImpact: 'Systems using RSA, ECC, or Diffie-Hellman are at risk from future quantum computers capable of breaking these algorithms.',
          technicalExplanation: 'NIST has standardised FIPS 203 (ML-KEM), FIPS 204 (ML-DSA), and FIPS 205 (SLH-DSA) as post-quantum algorithms. Organisations should inventory cryptographic usage and plan migration.',
          complianceRelevance: 'NCSC post-quantum guidance, NIST SP 800-208, and emerging regulatory expectations require PQC migration planning.',
          quantumReadinessRelevance: 'Critical quantum readiness gap. HNDL (Harvest Now Decrypt Later) attacks mean sensitive data encrypted today may be exposed when quantum computers mature.',
          recommendedFix: 'Conduct a cryptographic inventory for this target. Identify RSA/ECC/DH usage. Plan migration to NIST FIPS 203/204/205 compliant algorithms. Prioritise long-lived sensitive data.',
          evidenceRequired: 'Cryptographic inventory document, algorithm usage report, or PQC migration plan.',
        },
      },
    ],
  },
  {
    id: 'data_protection',
    label: 'Data Protection',
    icon: '🗄️',
    items: [
      {
        id: 'data_sensitivity_known',
        label: 'Data sensitivity level for this system is documented',
        hint: 'The types and sensitivity of data processed by this system are classified.',
        category: 'Data Protection',
        riskIfNo: 'Medium',
        appliesTo: [],
      },
      {
        id: 'gdpr_dpa',
        label: 'GDPR / data protection compliance requirements have been assessed',
        hint: 'If this system processes personal data, GDPR/DPA obligations have been reviewed.',
        category: 'Compliance Gap',
        riskIfNo: 'High',
        appliesTo: [],
      },
      {
        id: 'data_minimisation',
        label: 'Data minimisation principle is applied — only necessary data is collected',
        hint: 'The system does not collect or retain more data than needed for its stated purpose.',
        category: 'Data Protection',
        riskIfNo: 'Medium',
        appliesTo: [],
      },
      {
        id: 'retention_policy',
        label: 'Data retention and deletion policy exists for this system',
        hint: 'A policy defines how long data is kept and how it is securely deleted.',
        category: 'Data Protection',
        riskIfNo: 'Medium',
        appliesTo: [],
      },
    ],
  },
  {
    id: 'backup_recovery',
    label: 'Backup & Recovery',
    icon: '💾',
    items: [
      {
        id: 'backups_exist',
        label: 'Regular automated backups exist for this system',
        hint: 'Backups are taken regularly, automatically, and tested periodically.',
        category: 'Backup / Recovery',
        riskIfNo: 'High',
        appliesTo: [],
        finding: {
          title: 'Regular backups not confirmed for this target',
          businessImpact: 'Without verified backups, a security incident, ransomware attack, or system failure could result in permanent data loss.',
          technicalExplanation: 'Regular automated backups, stored separately from the primary system, are essential for business continuity and ransomware resilience.',
          complianceRelevance: 'Required by ISO 27001, NCSC Cyber Essentials, GDPR (for data availability), and most business continuity frameworks.',
          quantumReadinessRelevance: 'Backup encryption should use quantum-resistant algorithms where long-term confidentiality is required.',
          recommendedFix: 'Implement automated daily backups with offsite/cloud storage. Test restoration quarterly. Encrypt backups with AES-256 or stronger.',
          evidenceRequired: 'Backup policy document, backup configuration screenshot, or recent restore test evidence.',
        },
      },
      {
        id: 'backup_tested',
        label: 'Backup restoration has been tested',
        hint: 'A restore has been performed and documented within the last 12 months.',
        category: 'Backup / Recovery',
        riskIfNo: 'High',
        appliesTo: [],
      },
      {
        id: 'rto_rpo_defined',
        label: 'Recovery Time Objective (RTO) and Recovery Point Objective (RPO) are defined',
        hint: 'The organisation knows how quickly they need to recover and how much data loss is acceptable.',
        category: 'Backup / Recovery',
        riskIfNo: 'Medium',
        appliesTo: [],
      },
    ],
  },
  {
    id: 'vendor_risk',
    label: 'Vendor Risk',
    icon: '🏭',
    items: [
      {
        id: 'third_party_deps',
        label: 'Third-party dependencies and vendors have been reviewed',
        hint: 'Key software libraries, plugins, APIs, and vendors used by this system have been assessed for security posture.',
        category: 'Vendor Risk',
        riskIfNo: 'Medium',
        appliesTo: [],
      },
      {
        id: 'vendor_sla',
        label: 'Security SLAs or agreements exist with critical vendors',
        hint: 'Contracts or agreements with key vendors include security and incident notification clauses.',
        category: 'Vendor Risk',
        riskIfNo: 'Medium',
        appliesTo: [],
      },
      {
        id: 'supply_chain_review',
        label: 'Supply chain / software supply chain has been reviewed',
        hint: 'Open source dependencies, software build pipelines, and deployment sources are reviewed for supply chain risk.',
        category: 'Vendor Risk',
        riskIfNo: 'Medium',
        appliesTo: [],
      },
    ],
  },
  {
    id: 'quantum_readiness',
    label: 'Quantum Readiness',
    icon: '⚛️',
    items: [
      {
        id: 'crypto_inventory',
        label: 'Cryptographic algorithm inventory exists for this system',
        hint: 'All cryptographic algorithms used (RSA, ECC, AES, SHA, etc.) are inventoried.',
        category: 'Quantum Readiness',
        riskIfNo: 'High',
        appliesTo: [],
        finding: {
          title: 'Cryptographic inventory not completed for this target',
          businessImpact: 'Without a cryptographic inventory, it is impossible to plan post-quantum migration or assess quantum exposure.',
          technicalExplanation: 'A cryptographic inventory lists all algorithms, key sizes, certificates, protocols, and their usage across the system. This is the first step in any PQC migration programme.',
          complianceRelevance: 'Required by NIST SP 800-208 migration guidance, NCSC PQC guidance, and emerging regulatory frameworks.',
          quantumReadinessRelevance: 'Critical foundation for quantum readiness — without an inventory, migration cannot be planned.',
          recommendedFix: 'Conduct a cryptographic inventory: list all TLS usage, certificate algorithms, database encryption, code signing, and authentication tokens. Identify RSA, ECC, and Diffie-Hellman usage.',
          evidenceRequired: 'Cryptographic inventory spreadsheet or documentation.',
        },
      },
      {
        id: 'hndl_awareness',
        label: 'Harvest Now Decrypt Later (HNDL) risk has been assessed',
        hint: 'The organisation understands that adversaries may be collecting encrypted data today to decrypt later with quantum computers.',
        category: 'Quantum Readiness',
        riskIfNo: 'High',
        appliesTo: [],
      },
      {
        id: 'pqc_migration_plan',
        label: 'A post-quantum migration plan or roadmap exists',
        hint: 'A documented plan exists to migrate to NIST FIPS 203/204/205 compliant algorithms.',
        category: 'Quantum Readiness',
        riskIfNo: 'High',
        appliesTo: [],
        finding: {
          title: 'No post-quantum migration plan found for this target',
          businessImpact: 'Without a migration plan, quantum-vulnerable systems will remain exposed as the quantum threat matures.',
          technicalExplanation: 'NIST has finalised post-quantum standards: FIPS 203 (ML-KEM for key encapsulation), FIPS 204 (ML-DSA for signatures), FIPS 205 (SLH-DSA for signatures). Organisations should be planning migration now.',
          complianceRelevance: 'NCSC recommends organisations develop PQC migration plans now. Regulatory guidance is evolving.',
          quantumReadinessRelevance: 'Core quantum readiness gap.',
          recommendedFix: 'Develop a PQC migration roadmap. Prioritise long-lived, sensitive data. Identify hybrid classical+PQC deployment opportunities. Engage with certificate authorities and library vendors on PQC support timelines.',
          evidenceRequired: 'PQC migration plan document or roadmap.',
        },
      },
      {
        id: 'crypto_agility',
        label: 'Cryptographic agility is considered — algorithms can be swapped without full rebuild',
        hint: 'The system is designed so cryptographic algorithms can be updated without requiring a complete rewrite.',
        category: 'Quantum Readiness',
        riskIfNo: 'Medium',
        appliesTo: [],
      },
    ],
  },
  {
    id: 'evidence',
    label: 'Evidence & Documentation',
    icon: '📁',
    items: [
      {
        id: 'security_policy',
        label: 'A security policy covering this system exists',
        hint: 'A written security policy addresses this system or class of system.',
        category: 'Evidence Gap',
        riskIfNo: 'Medium',
        appliesTo: [],
      },
      {
        id: 'pen_test_recent',
        label: 'A penetration test or independent security review has been conducted within the last 12 months',
        hint: 'An external or internal authorised security review has assessed this system.',
        category: 'Evidence Gap',
        riskIfNo: 'Medium',
        appliesTo: [],
      },
      {
        id: 'vulnerability_management',
        label: 'A vulnerability management or patching process exists for this system',
        hint: 'Security patches are applied in a timely manner. A process governs vulnerability prioritisation.',
        category: 'Operational Risk',
        riskIfNo: 'High',
        appliesTo: [],
      },
      {
        id: 'incident_response',
        label: 'An incident response plan covers this system',
        hint: 'A documented plan exists for responding to security incidents affecting this system.',
        category: 'Operational Risk',
        riskIfNo: 'Medium',
        appliesTo: [],
      },
    ],
  },
];

// ─── Check Answer Values ───────────────────────────────────────────────────────
export const CHECK_ANSWERS = [
  { value: 'yes',      label: 'Yes',           icon: '✅' },
  { value: 'no',       label: 'No',            icon: '❌' },
  { value: 'unknown',  label: 'Unknown',       icon: '❓' },
  { value: 'na',       label: 'Not Applicable',icon: '➖' },
];

// ─── Demo Targets ─────────────────────────────────────────────────────────────
export const DEMO_TARGETS = [
  {
    id: 'demo_target_meridian_portal',
    clientId: 'demo_client_meridian',
    targetName: 'Meridian Client Portal',
    targetType: 'web_app',
    targetUrl: 'https://portal.meridian-legal.example.com',
    businessOwner: 'Sarah Chen, Managing Partner',
    technicalContact: 'IT Support Team',
    assessmentPurpose: 'Annual security review for ISO 27001 alignment',
    assessmentScope: 'Client-facing portal including authentication, document access, and case management.',
    scanMode: 'passive_web',
    status: 'recommendations_generated',
    tags: ['legal', 'client-data', 'gdpr'],
    notes: 'High priority — handles sensitive legal documents and client PII.',
    authorisationConfirmed: true,
    authorisationConfirmedAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    authorisedBy: 'Sarah Chen, Managing Partner',
    createdAt: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo_target_apex_api',
    clientId: 'demo_client_apex',
    targetName: 'Apex MSP Customer API',
    targetType: 'api',
    targetUrl: 'https://api.apex-managed.example.com',
    businessOwner: 'James Whitmore, CTO',
    technicalContact: 'Platform Engineering',
    assessmentPurpose: 'Security readiness review ahead of SOC 2 audit',
    assessmentScope: 'REST API serving managed service customers. Includes authentication, rate limiting, and data access endpoints.',
    scanMode: 'api_config',
    status: 'evidence_required',
    tags: ['api', 'saas', 'soc2'],
    notes: 'Customer-facing API — critical for business operations.',
    authorisationConfirmed: true,
    authorisationConfirmedAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    authorisedBy: 'James Whitmore, CTO',
    createdAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    isDemo: true,
  },
];

export const DEMO_FINDINGS = [
  {
    id: 'demo_finding_001',
    targetId: 'demo_target_meridian_portal',
    title: 'Multi-Factor Authentication (MFA) not enforced for all accounts',
    category: 'Authentication',
    riskLevel: 'Critical',
    businessImpact: 'Without MFA enforcement, client accounts are vulnerable to credential-based attacks that could expose sensitive legal documents.',
    technicalExplanation: 'MFA is available but not enforced. Privileged accounts and external client access should require MFA as a minimum.',
    complianceRelevance: 'Required by ISO 27001, NCSC Cyber Essentials Plus, and GDPR Article 32 (appropriate technical measures).',
    quantumReadinessRelevance: 'Password-based authentication is particularly vulnerable post-quantum. MFA is an important interim control.',
    recommendedFix: 'Enforce MFA for all accounts — start with admin/privileged accounts, then extend to all client-facing users.',
    evidenceRequired: 'MFA enforcement policy, screenshot of authentication settings, or identity provider configuration.',
    priority: 1,
    confidenceLevel: 'High',
    status: 'Open',
    createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo_finding_002',
    targetId: 'demo_target_meridian_portal',
    title: 'Post-quantum cryptography migration not assessed',
    category: 'Quantum Readiness',
    riskLevel: 'High',
    businessImpact: 'Legal data encrypted with RSA or ECC today may be vulnerable to decryption when quantum computers mature (HNDL risk).',
    technicalExplanation: 'No cryptographic inventory or PQC migration plan exists. RSA and ECC usage in TLS and document signing needs to be assessed.',
    complianceRelevance: 'NCSC post-quantum guidance recommends PQC migration planning now. Emerging regulatory requirements will follow.',
    quantumReadinessRelevance: 'Critical — sensitive legal data has long confidentiality requirements making HNDL risk severe.',
    recommendedFix: 'Conduct a cryptographic inventory. Develop a PQC migration roadmap. Prioritise TLS certificate algorithm migration and document encryption.',
    evidenceRequired: 'Cryptographic inventory document and PQC migration plan.',
    priority: 2,
    confidenceLevel: 'High',
    status: 'Open',
    createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    isDemo: true,
  },
];

export const DEMO_SCORES = [
  {
    id: 'demo_score_001',
    targetId: 'demo_target_meridian_portal',
    securityReadinessScore: 34,
    quantumReadinessScore: 18,
    evidenceCompletenessScore: 45,
    complianceReadinessScore: 29,
    overallRiskLevel: 'High',
    positiveFactors: ['HTTPS enforced', 'Privacy policy present', 'Backups exist'],
    negativeFactors: ['MFA not enforced', 'No PQC plan', 'CSP header missing', 'No crypto inventory'],
    missingEvidence: ['MFA configuration documentation', 'Cryptographic inventory', 'Certificate details', 'Penetration test report'],
    priorityFixes: ['Enforce MFA for all accounts', 'Conduct cryptographic inventory', 'Add CSP and security headers', 'Develop PQC migration plan'],
    confidenceLevel: 'Medium',
    calculatedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    isDemo: true,
  },
];
